routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::group(['prefix' => 'admin','middleware' => 'auth'], function () {
    //Dashboard
    Route::get('/dashboard','Admin\DashboardController@index')->name('admin.dashboard.index');
    //User
    Route::get('/users/getdatatables','Admin\UserController@getdatatables')->name('admin.users.getdatatables');
    Route::resource('users','Admin\UserController',['as'=>'admin']);
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Laravel\Passport\HasApiTokens;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use Spatie\Permission\Models\Role;

class User extends Authenticatable
{
    use Notifiable,HasApiTokens,HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'phone', 'gender', 'dob', 'user_role_id', 'status', 
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    
    /*
    |------------------------------------------------------------------------------------
    | Validations
    |------------------------------------------------------------------------------------
    */
    public static function rules($update = false, $id = null)
    {
        $commun = [
            'name'              => "required",
            'phone'             => "required",
            'email'             => "required|email|max:255|unique:users,email,$id",
            'password'          => 'nullable|min:6|confirmed',
            'gender'            => 'required',
            'dob'               => 'required|date',
            'status'            => 'required',
            'user_role_id'      => 'required',
            'upload_profile'    => 'nullable|file|image|mimes:jpeg,png,gif,webp|max:2048',
        ];

        if ($update) {
            return $commun;
        }

        return array_merge($commun, [
            'email'    => 'required|email|max:255|unique:users',
            'password' => 'required|confirmed|min:6',
        ]);
    }
    public static function getGender($id=null)
    {
        $v[1] = "Male";
        $v[2] = "Female";
        if($id){
            return $v[$id];
        }
        return $v;
    }

    public static function getStatus($id=null)
    {
        $v[1] = "Active";
        $v[0] = "Inactive";
        if($id){
            return $v[$id];
        }
        return $v;
    }
     /*
    |------------------------------------------------------------------------------------
    | Attributes
    |------------------------------------------------------------------------------------
    */
    public function setPasswordAttribute($value='')
    {
        $this->attributes['password'] = bcrypt($value);
    }
    
    public function getProfilePathAttribute($value)
    {
        if (!$value) {
            return 'http://placehold.it/160x160';
        }
    
        return $value;
    }
    public function getRoleName()
    {
        $role = Role::find($this->user_role_id);
        return $role->name;
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Role;
use App\User;
use Illuminate\Support\Facades\Input;
use Validator, Redirect, DataTables, Auth, Toastr,Storage,File;
use App\Helpers\common;
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.users.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //get roles, gender, status pre-defined data
        $data = $this->modelData();
        return view('admin.users.create',['roles'=>$data['roles'],'genders'=>$data['genders'],'statuses'=>$data['statuses']]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //server side validation
        $validator = Validator::make($request->all(),User::rules());
        if ($validator->fails()) {
            return Redirect::back()->withInput(Input::all())->withErrors($validator);
        }
        //custom validation
        $errors = $this->customValidation($request->all());
        if(!empty($errors)){
            return Redirect::back()->withInput(Input::all())->withErrors($errors);
        }
        //end validation
        
        //create user
        $user = User::create($request->all());

        //if has upload image
        $file = $request->file('upload_profile');
        if($file){   
            $profile_path = uploadFile($file,'users');
            $user->profile_path = $profile_path;
            $user->save();
        }

        //Display Message and Redirect
        $role = Role::find($request->input('user_role_id'));
        Toastr::info("Create $role->name Successfully!");
        return redirect()->route('admin.users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = \App\User::find($id);
        $user->dob = \Carbon\Carbon::parse($user->dob)->format('Y-m-d');
        $data = $this->modelData();
        return view('admin.users.edit',['user'=>$user,'roles'=>$data['roles'],'genders'=>$data['genders'],'statuses'=>$data['statuses']]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //server side validation
        $validator = Validator::make($request->all(),User::rules(true,$id));
        if ($validator->fails()) {
            return Redirect::back()->withInput(Input::all())->withErrors($validator);
        }
        //custom validation
        $errors = $this->customValidation($request->all());
        if(!empty($errors)){
            return Redirect::back()->withInput(Input::all())->withErrors($errors);
        }
        //end validation

        $user = User::findOrFail($id);
        $user->update($request->all());

        //if has upload image
        $file = $request->file('upload_profile');
        if($file){   
            //remove existing file
            removeFile($user->profile_path);
            //upload image and set updated path
            $profile_path = uploadFile($file,'users');
            $user->profile_path = $profile_path;
            $user->save();
        }
        //display message and done
        Toastr::info('Update User Successfully!');
        return redirect()->route('admin.users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        \DB::table('users')->where('id',$id)->delete();
        Toastr::info('User is removed successfully!');
        return redirect()->route('admin.users.index');
    }

    public function getdatatables()
    {
        $user = Auth::user();
        $users = \App\User::select(['id', 'name', 'email', 'phone', 'user_role_id', 'status', 'created_at']);
        return DataTables::of($users)
            ->addColumn('action', function ($user) {
            })
            ->setTransformer(new \App\Transformers\UserTransformer)
            ->make(true);
    }

    public function customValidation($request)
    {
        $errors = array();
        if($request['gender'] == -1){
            $errors[] = "The field gender is required!";
        }
        if($request['status'] == -1){
            $errors[] = "The field status is required!";
        }
        if($request['user_role_id'] == -1){
            $errors[] = "The field role is required!";
        }
        return $errors;
    }
    public function modelData()
    {
        $roles = Role::get();
        $genders = \App\User::getGender();
        $statuses = \App\User::getStatus();
        return ['roles'=>$roles,'genders'=>$genders,'statuses'=>$statuses];
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layouts.master')

@section('title')
    Create New User | {{ config('app.name') }}
@endsection

@section('css')
    
@endsection

@section('header')
<header class="head">
    <div class="main-bar">
        <div class="row">
            <div class="col-lg-6">
                <h4 class="nav_top_align">
                    <i class="fa fa-users"></i>
                    User List
                </h4>
            </div>
            <div class="col-lg-6">
                <div class="float-right">
                    <ol class="breadcrumb nav_breadcrumb_top_align">
                        <li class="breadcrumb-item">
                            <a href="{{ route('admin.dashboard.index') }}">
                                <i class="fa fa-home" data-pack="default" data-tags=""></i>
                                Dashboard
                            </a>
                        </li>
                        <li class="breadcrumb-item">
							<a href="{{ route('admin.users.index') }}">Users</a>
						</li>
						<li class="breadcrumb-item active">
								Create Users
						</li>
                    </ol>
                    </div>
            </div>
        </div>
    </div>
</header>
@endsection

@section('content')
<div class="card">
    <div class="card-header bg-white">
        Create New User
    </div>
    <div class="card-block">
        <form action="{{ route('admin.users.store') }}" method="post" enctype="multipart/form-data">
            @method('POST')
            @csrf
            @include('admin.users.form')
        </form>
    </div>
</div>
@stop

@section('js')
	<script>
		$(document).ready(function(){
            var date_input=$('input[name="dob"]'); //our date input has the name "date"
            var options={
                format: 'yyyy-mm-dd',
                todayHighlight: true,
                autoclose: true,
            };
            date_input.datepicker(options);
		})
	</script>
@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.master')

@section('title')
    Edit User | {{ config('app.name') }}
@endsection

@section('css')
    
@endsection

@section('header')
<header class="head">
    <div class="main-bar">
        <div class="row">
            <div class="col-lg-6">
                <h4 class="nav_top_align">
                    <i class="fa fa-users"></i>
                    Users Module
                </h4>
            </div>
            <div class="col-lg-6">
                <div class="float-right">
                    <ol class="breadcrumb nav_breadcrumb_top_align">
                        <li class="breadcrumb-item">
                            <a href="{{ route('admin.dashboard.index') }}">
                                <i class="fa fa-home" data-pack="default" data-tags=""></i>
                                Dashboard
                            </a>
                        </li>
                        <li class="breadcrumb-item">
							<a href="{{ route('admin.users.index') }}">Users</a>
						</li>
						<li class="breadcrumb-item active">
								Edit User
						</li>
                    </ol>
                    </div>
            </div>
        </div>
    </div>
</header>
@endsection

@section('content')
<div class="card">
	<div class="card-header bg-white">
		Edit User Data
	</div>
	<div class="card-block">
		<form action="{{ route('admin.users.update',$user->id) }}" method="post" enctype="multipart/form-data">
            @method('PUT')
            @csrf
			@include('admin.users.form')
		</form>
	</div>
</div>
	
@stop

@section('js')
	<script>
		$(document).ready(function(){
            var date_input=$('input[name="dob"]'); //our date input has the name "date"
            var options={
                format: 'yyyy-mm-dd',
                todayHighlight: true,
                autoclose: true,
            };
            date_input.datepicker(options);
		})
	</script>
@endsection

resources/views/admin/users/form.blade.php
<div class="row mB-40">
	<div class="col-sm-12">
		<div class="bgc-white p-20 bd">
			<div class="col-md-12 col-sm-12">
				<div class="row">
					<div class="col-md-6 col-sm-12">
						<div class="form-group">
							<label for="name">Full Name</label>
							<input type="text" class="form-control" name="name" placeholder="Full Name" value="{{ isset($user)?$user->name: old('name') }}">
						</div>
						@if(!isset($user))
						<div class="form-group">
							<label for="password">Password</label>
							<input type="password" class="form-control" name="password" placeholder="Password" }}">
						</div>
						<div class="form-group">
							<label for="confirmed">Confirm Password</label>
							<input type="password" class="form-control" name="password_confirmation" placeholder="Confirm Password" }}">
						</div>
						@endif
						<div class="form-group">
							<label for="dob">Date Of Birth</label>
							<input type="text" class="form-control" name="dob" placeholder="DOB"  value="{{ isset($user)?$user->dob:old('dob') }}">
						</div>
						<div class="form-group">
							<label for="user_role">Role</label>
							<select name="user_role_id" id="user_role_id" class="form-control">
								<option value="-1">Select Role</option>
								@php
									{{ $selectedvalue = (isset($user)) ? $user->user_role_id : old('user_role_id'); }}
								@endphp
								@foreach($roles as $role)
									<option value="{{$role['id']}}"  {{ $selectedvalue == $role['id'] ? 'selected="selected"' : '' }}>{{$role['name']}}</option>
								@endforeach 
							</select>
						</div>
					</div>
					<div class="col-md-6 col-sm-12">
						<div class="form-group">
							<label for="phone">Phone</label>
							<input type="number" class="form-control" name="phone" placeholder="Phone"  value="{{ isset($user)?$user->phone:old('phone') }}">
						</div>
						<div class="form-group">
							<label for="email">Email</label>
							<input type="email" class="form-control" name="email" placeholder="E-mail" value="{{ isset($user)?$user->email:old('email') }}">
						</div>
						<div class="form-group">
							<label for="gender">Gender</label>
							<select name="gender" id="gender" class="form-control">
								<option value="-1">Select Gender</option>
								@php
									{{ $selectedvalue = (isset($user)) ? $user->gender : old('gender'); }}
								@endphp
								@foreach($genders as $key=>$gender)
									<option value="{{$key}}"  {{ $selectedvalue == $key ? 'selected="selected"' : old('gender') }}>{{  $gender }}</option>
								@endforeach 
							</select>
						</div>
						<div class="form-group">
							<label for="status">Status</label>
							<select name="status" id="status" class="form-control">
								<option value="-1">Select Status</option>
								@php
									{{ $selectedvalue = (isset($user)) ? $user->status :-1; }}
									if(old('status')!==null)
									{
										$selectedvalue = old('status');
									}
								@endphp
								@foreach($statuses as $key=>$status)
									<option value="{{$key}}"  {{ $selectedvalue == $key ? 'selected="selected"' : '' }}>{{  $status }}</option>
								@endforeach 
							</select>
						</div>
					</div>
					<div class="col-md-12 col-sm-12">
						<div class="row">
							<div class="col-md-12 col-sm-12">
									<label for="upload_profile">Upload Profile Image</label>
									<input type="file" name="upload_profile" class="form-control" />
							</div>
							<div class="col-md-12 col-sm-12">
								@if(isset($user))
									<img src="{{ url($user->profile_path) }}" width="100px" height="auto" alt="image01.png"/>
								@endif
							</div>
						</div>						
					</div>
				</div>
				
				
				<div>
					<button type="submit" class="btn btn-primary">{{ !isset($user)? "Create" : "Update" }}</button>
					<a href="{{ url()->previous() }}" class="btn btn-danger"> Back </a>
				</div>
			</div>
		</div>  
	</div>
</div>

resources/views/admin/users/index.blade.php
@extends('admin.layouts.master')

@section('title')
    User List | {{ config('app.name') }}
@endsection

@section('css')
    <style>
    
    </style>
@endsection

@section('header')
<header class="head">
    <div class="main-bar">
        <div class="row">
            <div class="col-lg-6">
                <h4 class="nav_top_align">
                    <i class="fa fa-users"></i>
                    User List
                </h4>
            </div>
            <div class="col-lg-6">
                <div class="float-right">
                    <ol class="breadcrumb nav_breadcrumb_top_align">
                        <li class="breadcrumb-item">
                            <a href="{{ route('admin.dashboard.index') }}">
                                <i class="fa fa-home" data-pack="default" data-tags=""></i>
                                Dashboard
                            </a>
                        </li>
                        <li class="breadcrumb-item active">
                            Users
                        </li>
                    </ol>
                    </div>
            </div>
        </div>
    </div>
</header>
@endsection

@section('content')
<div class="outer">
        <div class="inner bg-light lter bg-container">
            <div class="row">
                <div class="col-12 data_tables">
                    <div class="card">
                        <div class="card-header bg-white">
                            <i class="fa fa-table"></i> Users Datatable 
                        </div>
                        <div class="card-block p-t-25">
                            <div class="">
                                <div class="pull-sm-right">
                                    <div class="tools pull-sm-right"></div>
                                </div>
                            </div>
                            <table id="table_users" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Phone</th>
                                        <th>User Role</th>
                                        <th>Status</th>
                                        <th>Created</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>            
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.inner -->
    </div>
    
@endsection

@section('js')
<script>
    $(document).ready(function(){
        var table_obj = $('#table_users').DataTable({
            processing: true,
            serverSide: true,
            searching: true,
            bLengthChange: true,
            ajax: {
                url: '{{ route('admin.users.getdatatables') }}',
            },
            columns: [
                {data: 'id', name: 'id'},
                {data: 'name', name: 'name'},
                {data: 'email', name: 'email'},
                {data: 'phone', name: 'phone'},
                {data: 'roles', name: 'roles', orderable: false, searchable: false},
                {data: 'status', name: 'status', orderable: false, searchable: false},
                {data: 'created_at', name: 'created_at'},
                {data: 'action', name: 'action'}
            ]
        });
        $('#table_users').on('click','.btn-danger', function(e){
            e.preventDefault();
            var id = $(this).data('id');
            if (confirm('Delete this user?')) {
                $("#delete_"+id).submit();
            } else {
                alert('It has been cancelled!');
            }
            
        })
    });
</script>
@endsection