routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::group(['prefix' => 'admin','middleware' => 'auth'], function () {
    //Dashboard
    Route::get('/dashboard','Admin\DashboardController@index')->name('admin.dashboard.index');
    //User
    Route::get('/users/getdatatables','Admin\UserController@getdatatables')->name('admin.users.getdatatables');
    Route::resource('users','Admin\UserController',['as'=>'admin']);
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Laravel\Passport\HasApiTokens;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use Spatie\Permission\Models\Role;

class User extends Authenticatable
{
    use Notifiable,HasApiTokens,HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'phone', 'gender', 'dob', 'user_role_id', 'status', 
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    
    /*
    |------------------------------------------------------------------------------------
    | Validations
    |------------------------------------------------------------------------------------
    */
    public static function rules($update = false, $id = null)
    {
        $commun = [
            'name'              => "required",
            'phone'             => "required",
            'email'             => "required|email|max:255|unique:users,email,$id",
            'password'          => 'nullable|min:6|confirmed',
            'gender'            => 'required',
            'dob'               => 'required|date',
            'status'            => 'required',
            'user_role_id'      => 'required',
            'upload_profile'    => 'nullable|file|image|mimes:jpeg,png,gif,webp|max:2048',
        ];

        if ($update) {
            return $commun;
        }

        return array_merge($commun, [
            'email'    => 'required|email|max:255|unique:users',
            'password' => 'required|confirmed|min:6',
        ]);
    }
    public static function getGender($id=null)
    {
        $v[1] = "Male";
        $v[2] = "Female";
        if($id){
            return $v[$id];
        }
        return $v;
    }

    public static function getStatus($id=null)
    {
        $v[1] = "Active";
        $v[0] = "Inactive";
        if($id){
            return $v[$id];
        }
        return $v;
    }
     /*
    |------------------------------------------------------------------------------------
    | Attributes
    |------------------------------------------------------------------------------------
    */
    public function setPasswordAttribute($value='')
    {
        $this->attributes['password'] = bcrypt($value);
    }
    
    public function getProfilePathAttribute($value)
    {
        if (!$value) {
            return 'http://placehold.it/160x160';
        }
    
        return $value;
    }
    public function getRoleName()
    {
        $role = Role::find($this->user_role_id);
        return $role->name;
    }
}

resources/views/admin/partials/menu.blade.php
<div class="media user-media dker">
        <div class="user-media-toggleHover">
            <span class="fa fa-user"></span>
        </div>
        <div class="user-wrapper">
            <a class="user-link" href="">
                <img class="media-object img-thumbnail user-img rounded-circle admin_img3" alt="User Picture" src="{{ url(Auth::user()->profile_path) }}"><p class="text-white user-info">Welcome {{ ucwords(Auth::user()->name) }}</p></a>

            {{-- <div class="search_bar col-lg-12">
                <div class="input-group">
                    <input type="search" class="form-control " placeholder="search">
                    <span class="input-group-btn">
                        <button class="btn without_border" type="button"><span class="fa fa-search" >
                        </span></button>
                    </span>
                </div>
            </div> --}}
        </div>
    </div>
    <!-- #menu -->
    <ul id="menu" class="bg-blue dker">
        <li class="menu-item" link="{{ route('admin.dashboard.index') }}">
            <a href="{{ route('admin.dashboard.index') }}" class="link">
                <i class="fa fa-home"></i>
                <span class="link-title">&nbsp;Dashboard</span>
            </a>
        </li>
        <li class="parent">
            <a href="javascript:;">
                <i class="fa fa-users"></i>
                <span class="link-title">&nbsp; Users</span>
                <span class="fa arrow"></span>
            </a>
            <ul>
                <li class="menu-item" link="{{ route('admin.users.create') }}">
                    <a href="{{ route('admin.users.create') }}">
                        <i class="fa fa-angle-right"></i>
                        &nbsp; Create User
                    </a>
                </li>
                <li class="menu-item" link="{{ route('admin.users.index') }}">
                    <a href="{{ route('admin.users.index') }}">
                        <i class="fa fa-angle-right"></i>
                        &nbsp; Users List
                    </a>
                </li>
            </ul>
        </li>
    </ul>
    <!-- /#menu -->

resources/views/admin/partials/navbar.blade.php
 <!-- .navbar -->
 <nav class="navbar navbar-static-top">
        <div class="container-fluid m-0">
            <a class="navbar-brand float-left text-center" href="index.html">
                <h4 class="text-white"><img src="{{ asset('img/logow.png') }}" class="admin_img" alt="logo"> {{ strtoupper(config('app.name')) }} ADMIN</h4>
            </a>
            <div class="menu">
            <span class="toggle-left" id="menu-toggle">
                <i class="fa fa-bars text-white"></i>
            </span>
            </div>
            <div class="topnav dropdown-menu-right float-right">
                {{-- <div class="btn-group">
                    <div class="notifications no-bg">
                        <a class="btn btn-default btn-sm messages" data-toggle="dropdown"> <i class="fa fa-envelope fa-1x text-white"></i>
                            <!--<span class="bg-warning message_tags">4</span>-->
                            <span class="badge badge-warning">8</span>
                        </a>
                        <div class="dropdown-menu drop_box_align" role="menu" id="messages_dropdown">
                            <div class="popover-title">You have 8 Messages</div>
                            <div id="messages">
                                <div class="data">
                                    <div class="row">
                                        <div class="col-2">
                                            <img src="{{ asset('img/mailbox_imgs/5.jpg') }}" class="message-img avatar rounded-circle"
                                                alt="avatar1"></div>
                                        <div class="col-10 message-data"><strong>hally</strong>
                                            sent you an image.
                                            <br>
                                            <small>add to timeline</small>
                                        </div>
                                    </div>
                                </div>
                                <div class="data">
                                    <div class="row">
                                        <div class="col-2">
                                            <img src="{{ asset('img/mailbox_imgs/8.jpg') }}" class="message-img avatar rounded-circle"
                                                alt="avatar1"></div>
                                        <div class="col-10 message-data"><strong>Meri</strong>
                                            invitation for party.
                                            <br>
                                            <small>add to timeline</small>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="popover-footer">
                                <a href="mail_inbox.html">Inbox</a>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="btn-group">
                    <div class="notifications messages no-bg">
                        <a class="btn btn-default btn-sm" data-toggle="dropdown"> <i class="fa fa-bell text-white"></i>
                            <!--<span class="bg-danger notification_tags">4</span>-->
                            <span class="badge badge-danger">9</span>
                        </a>
                        <div class="dropdown-menu drop_box_align" role="menu">
                            <div class="popover-title">You have 9 Notifications</div>
                            <div id="notifications">
                                <div class="data">
                                    <div class="row">
                                        <div class="col-2">
                                            <img src="{{ asset('img/mailbox_imgs/1.jpg') }}" class="message-img avatar rounded-circle"
                                                alt="avatar1"></div>
                                        <div class="col-10 message-data">
                                            <i class="fa fa-clock-o"></i>
                                            <strong>Remo</strong>
                                            sent you an image
                                            <br>
                                            <small class="primary_txt">just now.</small>
                                            <br>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="popover-footer">
                                <a href="#">View All</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="btn-group">
                    <a class="btn btn-default btn-sm messages toggle-right">
                        &nbsp;
                        <i class="fa fa-cog text-white"></i>
                        &nbsp;
                    </a>
                </div> --}}
                <div class="btn-group">
                    <div class="user-settings no-bg">
                        <button type="button" class="btn btn-default no-bg micheal_btn" data-toggle="dropdown">
                            <img src="{{ url(Auth::user()->profile_path) }}" class="admin_img2 rounded-circle avatar-img" alt="avatar"> <strong>{{ ucwords(Auth::user()->name) }}</strong>
                            <span class="fa fa-sort-down white_bg"></span>
                        </button>
                        <div class="dropdown-menu admire_admin">
                            <a class="dropdown-item title" href="#">
                                    {{ Auth::user()->getRoleName() }}</a>
                            {{-- <a class="dropdown-item" href="edit_user.html"><i class="fa fa-cogs"></i>
                                Account Settings</a> --}}
                            <a class="dropdown-item logout" href="#"><i class="fa fa-sign-out"></i>
                                Log Out</a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="hidden" style="display:none">
                                @csrf
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            {{-- <div class="navbar-toggleable-sm col-xl-6 col-lg-6 hidden-md-down float-right  top_menu" id="nav-content">
                <ul class="nav navbar-nav top_menubar">
                    <li class="nav-item">
                        <a class="nav-link text-white" href="mail_inbox.html">
                            <i class="fa fa-inbox"></i> <span class="quick_text">Inbox</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="mail_compose.html">
                            <i class="fa fa fa-edit"></i> <span class="quick_text">Compose</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="maps.html">
                            <i class="fa fa-map-marker"></i> <span class="quick_text">Maps</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="gallery.html">
                            <i class="fa fa-picture-o"></i> <span class="quick_text">Gallery</span>
                        </a>
                    </li>
                </ul>
            </div> --}}
        </div>

        <!-- /.container-fluid --> </nav>
    <!-- /.navbar -->

resources/views/admin/partials/preloader.blade.php
<div class="preloader" style=" position: fixed;
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
    z-index: 100000;
    backface-visibility: hidden;
    background: #ffffff;">
    <div class="preloader_img" style="width: 200px;
        height: 200px;
        position: absolute;
        left: 48%;
        top: 48%;
        background-position: center;
        z-index: 999999">
            <img src="{{ asset('img/loader.gif') }}" style=" width: 40px;" alt="loading...">
    </div>
</div>

resources/views/admin/partials/sidebar.blade.php
<div id="right">
    <div class="right_content">
        <div class="alert alert-success white_txt">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong>Welcome Micheal
                <br/></strong>
            Set Your Skin Here. Checkout Admin Statistics. Good Day!.
        </div>
        <div class="well well-small dark">
            <div class="xs_skin_hide hidden-sm-up toggle-right"> <i class="fa fa-cog"></i></div>
            <h4 class="brown_txt">
            <span class="fa-stack fa-sm">
        <i class="fa fa-circle fa-stack-2x"></i>
        <i class="fa fa-paint-brush fa-stack-1x fa-inverse"></i>
        </span>
                Skins
            </h4>
            <br/>

            <div class="skinmulti_btn" onclick="javascript:loadjscssfile('blue_black_skin.css','css')">
                <div class="skin_blue skin_size"></div>
                <div class="skin_black skin_size"></div>
            </div>
            <div class="skinmulti_btn" onclick="javascript:loadjscssfile('green_black_skin.css','css')">
                <div class="skin_green skin_size"></div>
                <div class="skin_black skin_size"></div>
            </div>
            <div class="skinmulti_btn" onclick="javascript:loadjscssfile('purple_black_skin.css','css')">
                <div class="skin_purple skin_size"></div>
                <div class="skin_black skin_size"></div>
            </div>
            <div class="skinmulti_btn" onclick="javascript:loadjscssfile('orange_black_skin.css','css')">
                <div class="skin_orange skin_size"></div>
                <div class="skin_black skin_size"></div>
            </div>
            <div class="skinmulti_btn" onclick="javascript:loadjscssfile('red_black_skin.css','css')">
                <div class="skin_red skin_size"></div>
                <div class="skin_black skin_size"></div>
            </div>
            <div class="skinmulti_btn" onclick="javascript:loadjscssfile('mint_black_skin.css','css')">
                <div class="skin_mint skin_size"></div>
                <div class="skin_black skin_size"></div>
            </div>
            <div class="skinmulti_btn" onclick="javascript:loadjscssfile('brown_black_skin.css','css')">
                <div class="skin_brown skin_size"></div>
                <div class="skin_black skin_size"></div>
            </div>
            <div class="skinmulti_btn" onclick="javascript:loadjscssfile('black_skin.css','css')">
                <div class="skin_black skin_size"></div>
                <div class="skin_black skin_size"></div>
            </div>
            <div class="skin_btn skin_blue" onclick="javascript:loadjscssfile('blue_skin.css','css')"></div>
            <div class="skin_btn skin_green" onclick="javascript:loadjscssfile('green_skin.css','css')"></div>
            <div class="skin_btn skin_purple" onclick="javascript:loadjscssfile('purple_skin.css','css')"></div>
            <div class="skin_btn skin_orange" onclick="javascript:loadjscssfile('orange_skin.css','css')"></div>
            <div class="skin_btn skin_red" onclick="javascript:loadjscssfile('red_skin.css','css')"></div>
            <div class="skin_btn skin_mint" onclick="javascript:loadjscssfile('mint_skin.css','css')"></div>
            <div class="skin_btn skin_brown" onclick="javascript:loadjscssfile('brown_skin.css','css')"></div>
            <div class="skin_btn skin_black" onclick="javascript:loadjscssfile('black_skin.css','css')"></div>

        </div>
        <div class="well well-small dark">
            <h4 class="brown_txt margin15_bottom">
                <img src="{{ asset('img/admin.jpg') }}" width="32" height="32" class="rounded-circle avatar-img" alt="avatar"> &nbsp;Admin
                Statistics</h4>
            <br/>
            <ul class="list-unstyled">
                <li class="green_txt margin15_bottom">
        <span class="fa-stack fa-sm">
            <i class="fa fa-circle fa-stack-2x text-mint"></i>
            <i class="fa fa-lock fa-stack-1x fa-inverse"></i>
        </span>
                    &nbsp; Last Login
                    <span class="inlinesparkline float-right">2hrs Back</span>
                </li>
                <li class="warning_txt margin15_bottom">
                <span class="fa-stack fa-sm">
            <i class="fa fa-circle fa-stack-2x text-brown"></i>
            <i class="fa fa-pencil fa-stack-1x fa-inverse"></i>
            </span>
                    &nbsp; Pending Tasks
                    <span class="dynamicsparkline float-right">12</span>
                </li>
                <li class="primary_txt margin15_bottom">
                <span class="fa-stack fa-sm">
            <i class="fa fa-circle fa-stack-2x text-primary"></i>
            <i class="fa fa-cloud fa-stack-1x fa-inverse"></i>
            </span>
                    &nbsp; Weather Today
                    <span class="dynamicbar float-right">Rainy</span>
                </li>
                <li class="margin15_bottom">
                <span class="fa-stack fa-sm">
            <i class="fa fa-circle fa-stack-2x text-brown"></i>
            <i class="fa fa-calendar fa-stack-1x fa-inverse"></i>
            </span>
                    &nbsp; Events
                    <span class="inlinebar float-right">Team Out</span>
                </li>
                <li class="success_txt margin15_bottom">
                <span class="fa-stack fa-sm">
            <i class="fa fa-circle fa-stack-2x text-success"></i>
            <i class="fa fa-bell fa-stack-1x fa-inverse"></i>
            </span>
                    &nbsp; Notifications
                    <span class="inlinebar float-right">5</span>
                </li>
            </ul>
        </div>
        <div class="well well-small dark right_progressbar_section">
            <h4 class="brown_txt">
            <span class="fa-stack fa-sm">
            <i class="fa fa-circle fa-stack-2x text-brown"></i>
            <i class="fa fa-hand-o-down fa-stack-1x fa-inverse"></i>
            </span>
                Alerts
            </h4>
            <br/>
            <span>Sales Improvement</span>
            <span class="float-right">
        <small>20%</small>
    </span>

            <div class="progress">
                <div class="progress-bar bg-danger" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <span>Server Load</span>
            <span class="float-right">
        <small>80%</small>
    </span>
            <div class="progress">
                <div class="progress-bar bg-mint" role="progressbar" style="width: 75%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <span>Traffic Improvement</span>
            <span class="float-right">
        <small>55%</small>
    </span>
            <div class="progress">
                <div class="progress-bar bg-primary" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
        </div>
    </div>
</div>